{% set version = "1.3-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dosefinding
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DoseFinding_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DoseFinding/DoseFinding_{{ version }}.tar.gz
  sha256: 388383f13077bc2ef0f7f9d1817bc4a33d9d316a8a379295e25ccc819b1fe8c1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - r-base
    - r-ggplot2
    - r-lattice
    - r-mvtnorm
  run:
    - r-base
    - r-ggplot2
    - r-lattice
    - r-mvtnorm

test:
  commands:
    - $R -e "library('DoseFinding')"           # [not win]
    - "\"%R%\" -e \"library('DoseFinding')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=DoseFinding
  license: GPL-3.0-only
  summary: 'The DoseFinding package provides functions for the design and analysis of dose-finding experiments (with focus on pharmaceutical Phase II clinical trials). It provides functions for: multiple contrast tests, fitting non-linear dose-response models (using Bayesian and non-Bayesian estimation), calculating optimal
    designs and an implementation of the MCPMod methodology (Pinheiro et al. (2014) <doi:10.1002/sim.6052>).'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
