{% set version = "1.0-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dosefinding
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DoseFinding_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DoseFinding/DoseFinding_{{ version }}.tar.gz
  sha256: aa3059dfd2f419d648e6f0cfbf9b22647a7fa2d2dd7a72b8b28f0ba53656171b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - r-base
    - r-lattice
    - r-mvtnorm
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-lattice
    - r-mvtnorm

test:
  commands:
    - $R -e "library('DoseFinding')"           # [not win]
    - "\"%R%\" -e \"library('DoseFinding')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=DoseFinding
  license: GPL-3
  summary: 'The DoseFinding package provides functions for the design and analysis of dose-finding experiments (with focus on pharmaceutical Phase II clinical trials). It provides functions for: multiple contrast tests, fitting non-linear dose-response models (using Bayesian and non-Bayesian estimation), calculating optimal
    designs and an implementation of the MCPMod methodology (Pinheiro et al. (2014) <doi:10.1002/sim.6052>).'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: DoseFinding
# Type: Package
# Title: Planning and Analyzing Dose Finding Experiments
# Version: 0.9-17
# Date: 2019-11-15
# Authors@R: c( person("Bjoern", "Bornkamp", email = "bbnkmp@gmail.com", comment = c(ORCID = "0000-0002-6294-8185"), role = c("aut", "cre")), person("Jose", "Pinheiro", role = "ctb"), person("Frank", "Bretz", role = "ctb"))
# Depends: lattice, mvtnorm, R (>= 2.15.0)
# Suggests: numDeriv, Rsolnp, quadprog, parallel, multcomp
# Maintainer: Bjoern Bornkamp <bbnkmp@gmail.com>
# Description: The DoseFinding package provides functions for the design and analysis of dose-finding experiments (with focus on pharmaceutical Phase II clinical trials). It provides functions for: multiple contrast tests, fitting non-linear dose-response models (using Bayesian and non-Bayesian estimation), calculating optimal designs and an implementation of the MCPMod methodology (Pinheiro et al. (2014) <doi:10.1002/sim.6052>).
# License: GPL-3
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2019-11-15 19:22:34 UTC; bjoern
# Author: Bjoern Bornkamp [aut, cre] (<https://orcid.org/0000-0002-6294-8185>), Jose Pinheiro [ctb], Frank Bretz [ctb]
# Repository: CRAN
# Date/Publication: 2019-11-16 05:40:06 UTC
