appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ouiCVpYVQhGaWM56OVE30I75jhfgJAXmHN1HaXugX9/2KDYomzZYHttAEcrkZ7oA2fyLbMnNRRHi59thHth8QUvDzQEZqyhmuDGH1z9ux1qgQ5kH+0BCSTBMPDUYA7bscwmHB6ED/cvrySrd1tl/crqyM4LtlLTk+oAzBaqV9+XkgE+vHZBIzIZNtqijqmdV7olaItspzla6luT5/EfqxHkOK1T/bu1z2VaypEOdOu5gHCHvgF1nHKK9R65X3OsKMxEf4QOiNExBhQ09B70LPb0+BMcZlcL3m1GFQpHRxABuN80qD0MFcraY/E3aF1x1rndr57DRhCMRvPD66sNls0LImzrNFSzNiektRGt19A513JDNDlGYbAbylMzOk//IwSxvZODzMIjALOHef5pA/gFwr4A0XKKwnvBtcq2tk4Qbb/O64eOsSLSNeWnTJnVX04MUoKvIFTpwAj7/eP0fGmD5Z6KH9RtxeCduILgvlJueFng5WgwQacxTkxd1dnta/2PzPajey25qz7DPxvTqwD5QPZiqHZbmda3YZOXJagLb/zkpxsVgrOBeIDq/9S9toZqWqZHLNkW0YHsa7PrjHadEc7Xnes+5VfjvoLyugfgghgMkfr2SNK7RSxI3nDZjxdfbqxtzCilryGGrfts8797CqehDlR65HLBAFq1r158=}
